import { test, expect } from '@playwright/test'
import { evaluation } from './fixture'
test('complete issuance, clipboard, appeal, hold, reset and privacy', async ({ page, context }) => {
  const errors: string[] = []
  const outgoing: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  page.on('request', request => { if (!request.url().startsWith('http://127.0.0.1:4173')) outgoing.push(request.url()) })
  await context.grantPermissions(['clipboard-read', 'clipboard-write'])
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'AI 면죄부 발급 완료', exact: true })).toHaveCount(0)
  await page.getByRole('button', { name: '평가 프롬프트 복사', exact: true }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('evidence_available')
  await page.getByRole('button', { name: '내 생존 티어 확인하기' }).click()
  await expect(page.getByRole('alert')).toContainText('아직 판정문이 없습니다')
  await page.locator('#ai-response').fill('{broken json}')
  await page.getByRole('button', { name: '내 생존 티어 확인하기' }).click()
  await expect(page.getByRole('alert')).toContainText('평가 데이터를 찾지 못했습니다')
  await page.locator('#ai-response').fill('분석 결과\n```json\n' + JSON.stringify({...evaluation, total_score: 1}) + '\n```\n설명 끝')
  await page.getByRole('button', { name: '내 생존 티어 확인하기' }).click()
  await expect(page.locator('#result-heading')).toHaveText('AI 면죄부 발급 완료')
  await expect(page.locator('.correction-note')).toContainText('1점에서 95점으로')
  await expect(page.locator('.tier-display')).toContainText('AI 명예시민')
  await page.getByRole('button', { name: '면죄부 내용 복사' }).click()
  expect(await page.evaluate(() => navigator.clipboard.readText())).toContain('최종 점수: 95/100')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/certificate-' + test.info().project.name + '.png', fullPage: true })
  await page.getByRole('button', { name: '다른 AI에게 재심 요청' }).click()
  await expect(page.locator('.history details')).toHaveCount(1)
  await page.getByRole('radio', { name: 'Claude', exact: true }).check()
  await page.locator('#ai-response').fill(JSON.stringify({...evaluation, ai_name: 'Claude', evidence_available: false}))
  await page.getByRole('button', { name: '내 생존 티어 확인하기' }).click()
  await expect(page.locator('#result-heading')).toContainText('판정 보류')
  await page.getByRole('button', { name: '처음부터 다시 하기' }).click()
  await expect(page.locator('.history')).toHaveCount(0)
  await page.locator('#ai-response').fill('개인 원문 새로고침 검사')
  await page.reload()
  await expect(page.locator('#ai-response')).toHaveValue('')
  expect(await page.evaluate(() => ({local: localStorage.length, session: sessionStorage.length}))).toEqual({local: 0, session: 0})
  expect(outgoing).toEqual([])
  expect(errors).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/home-' + test.info().project.name + '.png', fullPage: true })
})
test('clipboard failure offers keyboard-accessible manual copy', async ({ page }) => {
  await page.goto('/')
  await page.evaluate(() => {
    Object.defineProperty(navigator, 'clipboard', { value: { writeText: () => Promise.reject(new Error('Denied')) }, configurable: true })
    document.execCommand = () => false
  })
  await page.getByRole('button', { name: '평가 프롬프트 복사', exact: true }).click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page.getByRole('textbox', { name: '직접 복사할 내용' })).toBeFocused()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '평가 프롬프트 복사', exact: true })).toBeFocused()
})
