import { expect, test } from '@playwright/test'

test('first visit chooses a language and preserves it on reload', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByText('Choose your language to step inside.')).toBeVisible()
  await page.getByRole('button', { name: 'English' }).click()
  await expect(page.getByRole('heading', { name: 'The world goes on. Even when you’re away.' })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'The world goes on. Even when you’re away.' })).toBeVisible()
  await expect(page.getByText('Choose your language to step inside.')).toHaveCount(0)
})

test('public world panels work on desktop and mobile without overflow', async ({ page }, info) => {
  await page.addInitScript(() => localStorage.setItem('ai_world_locale', 'ko-KR'))
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/')
  await expect(page.locator('.world-live-list li').first()).toBeVisible()
  await page.getByRole('button', { name: 'TEXT', exact: true }).click()
  await expect(page.locator('.reader-shell')).toBeVisible()
  await page.getByRole('button', { name: 'LIVE', exact: true }).click()
  await expect(page.locator('.map-character.is-selected')).toHaveCount(0)
  await expect(page.locator('.map-character-dot').first()).toHaveCSS('fill', 'rgb(255, 255, 255)')
  const mobile = info.project.name === 'mobile'
  await page.screenshot({ path: `test-results/world-${info.project.name}.png`, fullPage: true })
  if (mobile) await page.locator('.observatory-mobile-tabs').getByRole('button', { name: '등장인물' }).click()
  await page.locator('.observatory-person').first().click()
  await expect(page.locator('.observatory-character-detail')).toBeVisible()
  if (mobile) await page.locator('.observatory-mobile-tabs').getByRole('button', { name: '미니맵' }).click()
  await expect(page.locator('.map-character.is-selected')).toHaveCount(1)
  await expect(page.locator('.map-character.is-selected .map-character-dot')).toHaveCSS('fill', 'rgb(239, 83, 80)')
  if (await page.locator('.map-character').count() > 1) await expect(page.locator('.map-character:not(.is-selected) .map-character-dot').first()).toHaveCSS('fill', 'rgb(255, 255, 255)')
  await page.getByRole('button', { name: '선택 해제', exact: true }).click()
  await expect(page.locator('.map-character.is-selected')).toHaveCount(0)
  await page.locator('.map-character').first().click()
  await expect(page.locator('.map-character.is-selected')).toHaveCount(1)
  await page.locator('.observatory-map').screenshot({ path: `test-results/minimap-${info.project.name}.png` })
  await page.locator('.map-character.is-selected').click()
  await expect(page.locator('.map-character.is-selected')).toHaveCount(0)
  if (mobile) await page.locator('.observatory-mobile-tabs').getByRole('button', { name: '최근 사건' }).click()
  await page.locator('.observatory-events li button').first().click()
  await expect(page.locator('dialog[open]')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  expect(errors).toEqual([])
})

test('account session and locale survive reload and login', async ({ page }, info) => {
  await page.addInitScript(() => { if (!localStorage.getItem('ai_world_locale')) localStorage.setItem('ai_world_locale', 'ko-KR') })
  await page.goto('/')
  await page.getByRole('button', { name: '로그인' }).click()
  const dialog = page.locator('.world-auth-dialog')
  await dialog.getByRole('button', { name: '회원가입' }).click()
  const email = `reader-${info.project.name}-${Date.now()}@example.com`
  await dialog.getByLabel('닉네임').fill('World Reader')
  await dialog.getByLabel('이메일').fill(email)
  await dialog.getByLabel('비밀번호').fill('reader-test-password')
  await dialog.getByRole('button', { name: '회원가입', exact: true }).click()
  await expect(page.getByRole('button', { name: 'World Reader' })).toBeVisible()
  await page.getByLabel('언어', { exact: true }).selectOption('en-US')
  await expect(page.getByRole('heading', { name: 'The world goes on. Even when you’re away.' })).toBeVisible()
  await page.reload()
  await page.getByRole('button', { name: 'World Reader' }).click()
  await dialog.getByRole('button', { name: 'Log out', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Log in' })).toBeVisible()
  await page.getByLabel('Language', { exact: true }).selectOption('ko-KR')
  await page.getByRole('button', { name: '로그인' }).click()
  await dialog.getByLabel('이메일').fill(email)
  await dialog.getByLabel('비밀번호').fill('reader-test-password')
  await dialog.getByRole('button', { name: '로그인', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'The world goes on. Even when you’re away.' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'World Reader' })).toBeVisible()
})
