import { test, expect } from '@playwright/test'

test('admin account opens builder and rules without an operator token', async ({ page }, info) => {
  await page.addInitScript(() => localStorage.setItem('ai_world_locale', 'ko-KR'))
  await page.goto('/admin/world')
  await expect(page).toHaveURL(/\/login\?next=%2Fadmin%2Fworld$/)
  await expect(page.getByRole('heading', { name: '관리자 로그인' })).toBeVisible()
  await page.getByLabel('관리자 아이디 또는 이메일').fill('e2e-admin')
  await page.getByLabel('비밀번호').fill('wrong-password')
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveText('아이디 또는 비밀번호가 올바르지 않습니다.')
  await page.getByLabel('비밀번호').fill('e2e-admin-password')
  await page.getByRole('button', { name: '관리자 로그인', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/world$/)
  await expect(page.getByRole('heading', { name: '시즌 제어' })).toBeVisible()
  await expect(page.getByPlaceholder('x-admin-token')).toHaveCount(0)
  await page.getByRole('link', { name: 'WORLD RULE PRESET 관리' }).click()
  await expect(page.getByRole('button', { name: 'REALISTIC_WORLD', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'REALISTIC_WORLD', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'PRESET 편집 — REALISTIC_WORLD' })).toBeVisible()
  await page.getByRole('link', { name: 'WORLD 생성 Wizard로 돌아가기' }).click()
  await expect(page.getByRole('heading', { name: 'WORLD 목록' })).toBeVisible()
  if (info.project.name === 'mobile') return

  page.once('dialog', dialog => dialog.accept('E2E simulation'))
  await page.getByRole('button', { name: '+ 새 WORLD 만들기' }).click()
  await expect(page.getByLabel('WORLD 이름', { exact: true })).toHaveValue('E2E simulation')
  await page.getByRole('button', { name: '8. 시뮬레이션 설정', exact: true }).click()
  await page.getByRole('spinbutton', { name: 'Tick 간격 (초)', exact: true }).fill('3600')
  await page.getByRole('spinbutton', { name: 'Tick당 세계 시간 (분)', exact: true }).fill('1')
  await page.getByRole('button', { name: '초안 저장', exact: true }).click()
  await expect(page.getByRole('status')).toContainText('저장 완료')
  const id = page.url().split('/').at(-1)!
  const prefix = `/api/admin/world/drafts/${id}`
  const headers = { 'x-world-admin': '1' }
  const saved = await page.request.put(`${prefix}/places`, { headers, data: {
    places: ['A', 'B'].map(name => ({ tempId: name, name, isPublic: true, isDiscovered: true })),
    connections: [{ fromPlaceRef: 'A', toPlaceRef: 'B', travelTime: 15 }],
  } })
  expect(saved.ok()).toBeTruthy()
  const { draft } = await saved.json()
  const character = await page.request.post(`${prefix}/characters`, { headers, data: { name: 'Explorer', provider: 'openai', initialPlaceId: draft.places[0].id } })
  expect(character.ok()).toBeTruthy()
  await page.reload()
  await page.getByRole('button', { name: '10. WORLD START', exact: true }).click()
  page.once('dialog', dialog => dialog.accept())
  await page.getByRole('button', { name: 'START WORLD', exact: true }).click()
  await expect(page).toHaveURL(/\/admin\/world$/)
  await expect(page.getByText('데모 실행 ·', { exact: false })).toBeVisible()
  await page.getByRole('button', { name: '지금 1회 실행' }).click()
  await expect(page.getByText('1회 실행 완료', { exact: true })).toBeVisible()
  await expect(page.locator('.admin-table').getByText('Explorer', { exact: false }).first()).toBeVisible()
  const started = await (await page.request.get('/api/world/current')).json()
  expect(started.worldState.agents[0].publicState.locationId).toBe(draft.places[0].id)
  expect(started.worldState.engine.ongoingActions).toHaveLength(1)
  for (let minute = 0; minute < 15; minute++) expect((await page.request.post('/api/admin/world/tick', { headers })).ok()).toBeTruthy()
  const world = await (await page.request.get('/api/world/current')).json()
  expect(world.worldState.agents[0].publicState.locationId).toBe(draft.places[1].id)
  await page.getByRole('button', { name: '일시정지', exact: true }).click()
  await expect(page.getByRole('button', { name: '지금 1회 실행' })).toBeDisabled()
  await page.reload()
  await expect(page.getByRole('heading', { name: '시즌 제어' })).toBeVisible()
  await page.getByRole('button', { name: 'e2e-admin', exact: false }).click()
  await page.locator('.world-auth-dialog').getByRole('button', { name: '로그아웃', exact: true }).click()
  await expect(page).toHaveURL(/\/login\?next=%2Fadmin%2Fworld$/)
})
