import { test, expect } from '@playwright/test'
test('ten-step studio preserves edits, handles empty numbers, and reviews a runnable island on mobile and desktop',async({page},info)=>{
 await page.addInitScript(()=>localStorage.setItem('ai_world_locale','ko-KR'))
 await page.goto('/login')
 await page.getByLabel('관리자 아이디 또는 이메일').fill('e2e-admin')
 await page.getByLabel('비밀번호').fill('e2e-admin-password')
 await page.getByRole('button',{name:'관리자 로그인',exact:true}).click()
 await page.getByRole('link',{name:/세계 편집기 · 캐릭터/}).click()
 await page.getByRole('button',{name:'테스트 아일랜드 초안 만들기'}).click()
 await expect(page.getByRole('heading',{name:'테스트 아일랜드',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'8. 시뮬레이션 설정',exact:true}).click()
 const num=page.getByRole('spinbutton',{name:'동시 활성 캐릭터',exact:true})
 await num.fill('');await expect(num).toHaveValue('');await num.fill('5')
 await page.getByRole('button',{name:'동시 활성 캐릭터 감소',exact:true}).click();await expect(num).toHaveValue('4')
 await num.press('ArrowDown');await expect(num).toHaveValue('3')
 await page.getByRole('button',{name:'초안 저장',exact:true}).click()
 await expect(page.getByRole('status')).toContainText('저장 완료')
 await page.reload();await expect(page.getByRole('spinbutton',{name:'동시 활성 캐릭터',exact:true})).toHaveValue('3')
 await page.getByRole('button',{name:'6. 캐릭터 생성',exact:true}).click()
 await page.getByRole('textbox',{name:'직업',exact:true}).fill('항공 정비사')
 await page.getByRole('button',{name:'논리적',exact:true}).click()
 await page.getByRole('button',{name:'3. 장소',exact:true}).click()
 await page.getByRole('textbox',{name:'장소 이름',exact:true}).first().fill('별빛 중앙홀')
 await page.getByRole('button',{name:'9. 최종 검토',exact:true}).click()
 await page.getByRole('button',{name:'누락·충돌 검사',exact:true}).click()
 await expect(page.getByRole('status').filter({hasText:'시작 가능'})).toBeVisible()
 await page.getByRole('button',{name:'6. 캐릭터 생성',exact:true}).click()
 await expect(page.getByRole('textbox',{name:'직업',exact:true})).toHaveValue('항공 정비사')
 await expect(page.getByRole('button',{name:'논리적',exact:true})).toHaveAttribute('aria-pressed','true')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false)
 await page.getByRole('button',{name:'9. 최종 검토',exact:true}).click()
 await page.screenshot({path:`data/logs/studio-${info.project.name}.png`,fullPage:true})
})
